name: Compile Sources

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/compile-sources.yml
      - indexer
      - 'sources/*.url'

  schedule:
    - cron: '21 */1 * * *'

  workflow_dispatch:

jobs:
  index-sources:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Run Indexer
      id: indexer
      run: |
        # extract hosts from .url files
        hosts=$(find sources -name '*.url' -exec basename {} .url \;)

        # pipe hosts lists into indexer and pipe output to new JSON file
        echo $hosts | deno run --allow-env --allow-net --allow-read --allow-write indexer/main.ts > .messages.txt

        # save to output variable
        echo "commit_msg<<EOF" >> $GITHUB_OUTPUT
        echo "$(cat .messages.txt)" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Check if anything has changed
      run: |
        if ! git diff --quiet HEAD; then
          echo "Repository has changed, committing changes."
        else
          echo "Repository has not changed, exiting action."
          exit 0
        fi

    - name: Commit
      uses: EndBug/add-and-commit@v9
      if: success()
      with:
        add: '-A'
        default_author: github_actions
        message: ${{ steps.indexer.outputs.commit_msg }}
